name: manual Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: manual step
        run: echo "Hello, world!"
https://github.com/ashiq72/github-action/actions/workflows/02-manual-workflow.yml